version: '3.9'

services:
  app:
    container_name: backend-nest
    build: .
    ports:
      - '3000:3000'
    env_file: .env
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${PG_PORT}:${PG_PORT}
    volumes:
      - ./pgdata/data:/var/lib/postgresql/data
